name: Lint
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_build:
    name: Checks & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Run checks
        run: ./gradlew spotlessCheck lint detektMain

      - name: Build debug
        run: ./gradlew assembleDebug assembleDebugAndroidTest

      - name: Run tests
        run: ./gradlew testDebugUnitTest